### ISSUE TITLE
Building libffi: Os { code: 2, kind: NotFound, message: "No such file or directory" }

### ISSUE THREAD

**Issue by fzyzcjy** [tov/libffi-sys-rs#36]
Hi when running sample code from https://github.com/rsmpi/rsmpi using `cargo build` or `cargo run`, I encounter the following. I would appreciate it if I could know what to do. Thanks very much!

```
/code/trans_sort$ RUST_BACKTRACE=full cargo build
   Compiling libffi-sys v0.6.0
error: failed to run custom build command for `libffi-sys v0.6.0`

Caused by:
  process didn't exit successfully: `/code/trans_sort/target/debug/build/libffi-sys-3cdb33c6e0567cd9/build-script-build` (exit code: 101)
  --- stdout
  libtoolize: putting auxiliary files in '.'.
  libtoolize: copying file './ltmain.sh'
  libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
  libtoolize: copying file 'm4/libtool.m4'
  libtoolize: copying file 'm4/ltoptions.m4'
  libtoolize: copying file 'm4/ltsugar.m4'
  libtoolize: copying file 'm4/ltversion.m4'
  libtoolize: copying file 'm4/lt~obsolete.m4'
  checking build system type... x86_64-pc-linux-gnu
  checking host system type... x86_64-pc-linux-gnu
  checking target system type... x86_64-pc-linux-gnu
  continue configure in default builddir "./x86_64-unknown-linux-gnu"
  ....exec /bin/bash .././configure "--srcdir=.." "--enable-builddir=x86_64-unknown-linux-gnu" "linux
  gnu"
  checking build system type... x86_64-pc-linux-gnu
  checking host system type... x86_64-pc-linux-gnu
  checking target system type... x86_64-pc-linux-gnu
  checking for gsed... sed
  checking for a BSD-compatible install... /usr/bin/install -c
  checking whether build environment is sane... yes
  checking for a thread-safe mkdir -p... /bin/mkdir -p
  checking for gawk... no
  checking for mawk... mawk
  checking whether make sets $(MAKE)... no
  checking whether make supports nested variables... no
  checking for gcc... gcc
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables... 
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether we are using the GNU C compiler... yes
  checking whether gcc accepts -g... yes
  checking for gcc option to accept ISO C89... none needed
  checking whether gcc understands -c and -o together... yes
  checking for style of include used by make... none
  checking dependency style of gcc... none
  checking for g++... g++
  checking whether we are using the GNU C++ compiler... yes
  checking whether g++ accepts -g... yes
  checking dependency style of g++... none
  checking dependency style of gcc... none
  checking how to print strings... printf
  checking for a sed that does not truncate output... /bin/sed
  checking for grep that handles long lines and -e... /bin/grep
  checking for egrep... /bin/grep -E
  checking for fgrep... /bin/grep -F
  checking for ld used by gcc... /usr/bin/ld
  checking if the linker (/usr/bin/ld) is GNU ld... yes
  checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
  checking the name lister (/usr/bin/nm -B) interface... BSD nm
  checking whether ln -s works... no, using cp -pR
  checking the maximum length of command line arguments... 1572864
  checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
  checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
  checking for /usr/bin/ld option to reload object files... -r
  checking for objdump... objdump
  checking how to recognize dependent libraries... pass_all
  checking for dlltool... no
  checking how to associate runtime and link libraries... printf %s\n
  checking for ar... ar
  checking for archiver @FILE support... @
  checking for strip... strip
  checking for ranlib... ranlib
  checking command to parse /usr/bin/nm -B output from gcc object... ok
  checking for sysroot... no
  checking for a working dd... /bin/dd
  checking how to truncate binary pipes... /bin/dd bs=4096 count=1
  checking for mt... mt
  checking if mt is a manifest tool... no
  checking how to run the C preprocessor... gcc -E
  checking for ANSI C header files... yes
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking for dlfcn.h... yes
  checking for objdir... .libs
  checking if gcc supports -fno-rtti -fno-exceptions... no
  checking for gcc option to produce PIC... -fPIC -DPIC
  checking if gcc PIC flag -fPIC -DPIC works... yes
  checking if gcc static flag -static works... yes
  checking if gcc supports -c -o file.o... yes
  checking if gcc supports -c -o file.o... (cached) yes
  checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
  checking whether -lc should be explicitly linked in... no
  checking dynamic linker characteristics... GNU/Linux ld.so
  checking how to hardcode library paths into programs... immediate
  checking whether stripping libraries is possible... yes
  checking if libtool supports shared libraries... yes
  checking whether to build shared libraries... yes
  checking whether to build static libraries... yes
  checking how to run the C++ preprocessor... g++ -E
  checking for ld used by g++... /usr/bin/ld -m elf_x86_64
  checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
  checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
  checking for g++ option to produce PIC... -fPIC -DPIC
  checking if g++ PIC flag -fPIC -DPIC works... yes
  checking if g++ static flag -static works... yes
  checking if g++ supports -c -o file.o... yes
  checking if g++ supports -c -o file.o... (cached) yes
  checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
  checking dynamic linker characteristics... (cached) GNU/Linux ld.so
  checking how to hardcode library paths into programs... immediate
  checking size of size_t... 8
  checking for C compiler vendor... gnu
  checking whether C compiler accepts -fstrict-aliasing... yes
  checking whether C compiler accepts -ffast-math... yes
  checking for gcc architecture flag... 
  checking for x86 cpuid 0 output... 16:756e6547:6c65746e:49656e69
  checking for x86 cpuid 1 output... 906ea:2060800:defa2203:178bfbff
  checking whether C compiler accepts -march=core2... yes
  checking for gcc architecture flag... -march=core2
  checking whether C compiler accepts -O3 -fomit-frame-pointer -fstrict-aliasing -ffast-math -march=core2... yes
  checking CFLAGS for maximum warnings... -Wall
  checking whether to enable maintainer-specific portions of Makefiles... no
  checking sys/mman.h usability... yes
  checking sys/mman.h presence... yes
  checking for sys/mman.h... yes
  checking for mmap... yes
  checking for mkostemp... yes
  checking for sys/mman.h... (cached) yes
  checking for mmap... (cached) yes
  checking whether read-only mmap of a plain file works... yes
  checking whether mmap from /dev/zero works... yes
  checking for MAP_ANON(YMOUS)... yes
  checking whether mmap with MAP_ANON(YMOUS) works... yes
  checking for ANSI C header files... (cached) yes
  checking for memcpy... yes
  checking for size_t... yes
  checking for working alloca.h... yes
  checking for alloca... yes
  checking size of double... 8
  checking size of long double... 16
  checking whether byte ordering is bigendian... no
  checking assembler .cfi pseudo-op support... yes
  checking assembler supports pc related relocs... yes
  checking assembler .ascii pseudo-op support... yes
  checking assembler .string pseudo-op support... yes
  checking for _ prefix in compiled symbols... no
  checking toolchain supports unwind section type... yes
  checking whether .eh_frame section should be read-only... yes
  checking for __attribute__((visibility("hidden")))... yes
  checking that generated files are newer than configure... done
  configure: creating ./config.status
  config.status: creating include/Makefile
  config.status: creating include/ffi.h
  config.status: creating Makefile
  config.status: creating testsuite/Makefile
  config.status: creating man/Makefile
  config.status: creating libffi.pc
  config.status: creating fficonfig.h
  config.status: linking ../src/x86/ffitarget.h to include/ffitarget.h
  config.status: executing buildir commands
  config.status: create top_srcdir/Makefile guessed from local Makefile
  config.status: build in x86_64-unknown-linux-gnu (HOST=x86_64-unknown-linux-gnu)
  config.status: executing depfiles commands
  config.status: executing libtool commands
  config.status: executing include commands
  config.status: executing src commands

  --- stderr
  autoreconf: Entering directory `.'
  autoreconf: configure.ac: not using Gettext
  autoreconf: running: aclocal --force -I m4
  autoreconf: configure.ac: tracing
  autoreconf: running: libtoolize --copy --force
  autoreconf: running: /usr/bin/autoconf --force
  autoreconf: running: /usr/bin/autoheader --force
  autoreconf: running: automake --add-missing --copy --force-missing
  configure.ac:31: installing './compile'
  configure.ac:8: installing './config.guess'
  configure.ac:8: installing './config.sub'
  configure.ac:19: installing './install-sh'
  configure.ac:19: installing './missing'
  Makefile.am: installing './depcomp'
  Makefile.am:56: installing './mdate-sh'
  autoreconf: Leaving directory `.'
  thread 'main' panicked at 'Building libffi: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/cuhksz_csc/.cargo/registry/src/github.com-1ecc6299db9ec823/libffi-sys-0.6.0/build.rs:27:30
  stack backtrace:
     0:     0x55d813afc8c5 - backtrace::backtrace::libunwind::trace::h14d338b30b3ea0a7
                                 at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
     1:     0x55d813afc8c5 - backtrace::backtrace::trace_unsynchronized::h73ea91d74a3fd67f
                                 at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
     2:     0x55d813afc8c5 - std::sys_common::backtrace::_print_fmt::hd42948c952866e12
                                 at src/libstd/sys_common/backtrace.rs:78
     3:     0x55d813afc8c5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha8f928866ff7571e
                                 at src/libstd/sys_common/backtrace.rs:59
     4:     0x55d813b26dec - core::fmt::write::he0c1e5f7426d2718
                                 at src/libcore/fmt/mod.rs:1076
     5:     0x55d813af8f02 - std::io::Write::write_fmt::hf3afc6cfd57d0033
                                 at src/libstd/io/mod.rs:1537
     6:     0x55d813aff4e0 - std::sys_common::backtrace::_print::hfc0110703f3696fd
                                 at src/libstd/sys_common/backtrace.rs:62
     7:     0x55d813aff4e0 - std::sys_common::backtrace::print::h3f77c6990ddfaa22
                                 at src/libstd/sys_common/backtrace.rs:49
     8:     0x55d813aff4e0 - std::panicking::default_hook::{{closure}}::heae49580a8d62d75
                                 at src/libstd/panicking.rs:198
     9:     0x55d813aff22c - std::panicking::default_hook::hecc34e3f729e213c
                                 at src/libstd/panicking.rs:217
    10:     0x55d813affb23 - std::panicking::rust_panic_with_hook::he82f5d0644692441
                                 at src/libstd/panicking.rs:526
    11:     0x55d813aff71b - rust_begin_unwind
                                 at src/libstd/panicking.rs:437
    12:     0x55d813b254a1 - core::panicking::panic_fmt::h09c929f06bb87c98
                                 at src/libcore/panicking.rs:85
    13:     0x55d813b252c3 - core::option::expect_none_failed::h188f17af6c9f404b
                                 at src/libcore/option.rs:1269
    14:     0x55d813651969 - core::result::Result<T,E>::expect::h74d1ed625e19981f
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/result.rs:963
    15:     0x55d8136510dc - build_script_build::main::run_command::h11e9b2be338cc8d3
                                 at /home/cuhksz_csc/.cargo/registry/src/github.com-1ecc6299db9ec823/libffi-sys-0.6.0/build.rs:27
    16:     0x55d813650675 - build_script_build::main::h3bfc16c3e45662b9
                                 at /home/cuhksz_csc/.cargo/registry/src/github.com-1ecc6299db9ec823/libffi-sys-0.6.0/build.rs:50
    17:     0x55d813651c3b - std::rt::lang_start::{{closure}}::he72a22465750b8d1
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:67
    18:     0x55d813affef3 - std::rt::lang_start_internal::{{closure}}::h5d3ea623498f5f43
                                 at src/libstd/rt.rs:52
    19:     0x55d813affef3 - std::panicking::try::do_call::hac65e71be769a440
                                 at src/libstd/panicking.rs:348
    20:     0x55d813affef3 - std::panicking::try::hd4706e264bcf6712
                                 at src/libstd/panicking.rs:325
    21:     0x55d813affef3 - std::panic::catch_unwind::h948a0fb4a8b3ee82
                                 at src/libstd/panic.rs:394
    22:     0x55d813affef3 - std::rt::lang_start_internal::h72cc068ed2d0ac53
                                 at src/libstd/rt.rs:51
    23:     0x55d813651c17 - std::rt::lang_start::h4859f2d6fc25fa55
                                 at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:67
    24:     0x55d81365114a - main
    25:     0x7f91c3a98b97 - __libc_start_main
    26:     0x55d81364fdba - _start
    27:                0x0 - <unknown>
```

**Comment by yorickpeterse** [comment]
@fzyzcjy is it possible to upgrade to the latest versions of the libffi-sys and libffi crates? The build system has changed quite a bit since 0.6.0, so perhaps this has already been fixed since then.

**Comment by fzyzcjy** [comment]
@YorickPeterse Actually I have given up doing this and tried another solution. Anyway thanks!
